my:
  greeting: Hello World from config server (git-springCloudConfigClient-dev)
  list:
    values: One, Two, Three, Four, Five

db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200